/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:49fa21a9-a18c-4e3b-9f4f-a8471de54c27",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_wBScFK1Sp",
    "aws_user_pools_web_client_id": "43ahqli7ma7q1eot545dfodcoc",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://rv8uyog8p3.execute-api.eu-west-2.amazonaws.com/dev",
            "region": "eu-west-2"
        }
    ]
};


export default awsmobile;
